### ISSUE TITLE
What's the code license ?

### ISSUE THREAD

**Issue by bountyx** [cosmos/cosmos.network#117]
Thanks for sharing this, I wanted to ask what kind of license / level of sharing you guys are comfortable with if I were to fork this site, modify it and build off of it, for an unrelated project?

I plan on:
- Changing all images
- Changing all copy
- Having a dark color scheme but different primary & secondary colors
- Keeping navigational components and layout similar
- Preserving the space theme. I plan on making a webgl component to replace the solar system. It would be nice to be able to reuse the solar system with non-planetary objects
- Different fontstack
- Headless CMS support

I'm happy to contribute components back to this project and hit a few issues on your issue list as a contributor too.

**Comment by nassdonald** [comment]
Hi @bountyx. We're flattered you wish to fork the Cosmos website for your own project. 🙏  We had hoped that open-sourcing the website's source code would encourage community contributions, and would be in keeping with the spirit of transparency that we all value within the community.

We have not yet provided a license for this repository, so please bear with us while we figure out the most appropriate license in this case. Until then, I can comment on what would be most appropriate for avoiding any murky waters for the Cosmos trademark and brand…

* As you have stated, all copy and images must be changed/removed.
* The space theme is largely conveyed through the images, so in light of the above point, there wouldn't be much you could retain in that regard. That being said, the use of webGL to create dynamic space-themed visuals is a great idea – something we had hoped to experiment with ourselves, later down the road.
* You are free to use [Inter](https://rsms.me/inter/), since this is an open-source font.
* We are also planning to implement a CMS layer for various parts of the website that will be editable by copywriters, which will allow updating from markdown. If you have any input on that front, we're open to suggestions!

In any case, and in addition to the above points, we recommend you avoid using anything that would fall into the realms of plagiarizing the Cosmos brand identity or infringing upon the [trademark](https://cosmos.network/trademark) (forgive the old page) – at least for the time being.

**Comment by bountyx** [comment]
Awesome, thanks for the quick response. I'll hold off until you guys decide on a license. I do have some recommendations:

- For webGL I recommend https://modelviewer.dev/ by Google. Animated gltf files is the next iteration beyond specialized javascript and animation frameworks, but does require knowledge of 3d tools.
- For CMS, this one is tricky. My current site (check out www.apozy.com) uses Prismic.io, but at the time Strapi wasn't yet mature. Both solutions are great for marketing enablement where landing pages and A/B testing matters for layout variation. It may be a little overkill for only copywriting if the your layouts do not vary much. The key consideration here is if the resources can be prefetched and turned into static content at compile time for netlify deployment.
